apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-web-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: "python-app.test.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: python-web-svc
            port:
              number: 8080
