apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web
  labels:
    app: python-web-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-web
  template:
    metadata:
      labels:
        app: python-web
    spec:
      containers:
      - name: python-app
        image: leosol70/python-app:v4
        ports:
        - containerPort: 5000
